AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Step Functions Running Lambda functions

Globals:
  Function:
    Timeout: 15
    MemorySize: 256

Resources:
  # Lambda function summing input numbers
  StepFunctionExampleSumLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StepFunctionExampleSumLambda
      CodeUri: lambda_stepfunctions_src/lambda_stepfunctions_sum_src
      Handler: app.handler
      Runtime: python3.10
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
          AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
          REGION: us-east-1

  # Lambda function calculating the square root of input numbers
  StepFunctionExampleSquareLambda:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: StepFunctionExampleSquareLambda
      CodeUri: lambda_stepfunctions_src/lambda_stepfunctions_square_src
      Handler: app.handler
      Runtime: python3.10
      Environment:
        Variables:
          AWS_ACCESS_KEY_ID: DUMMYIDEXAMPLE
          AWS_SECRET_ACCESS_KEY: DUMMYEXAMPLEKEY
          REGION: us-east-1

  # Step Functions Machine running lambda functions
  StepFunctionsLambdaStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      StateMachineName: StepFunctionsLambdaStateMachine
      DefinitionString: !Sub
        - |-
          {
            "StartAt": "Lambda Sum State",
            "States": {
              "Lambda Sum State": {
                "Type": "Task",
                "Resource": "${SumLambdaArn}",
                "Next": "Wait State",
                "InputPath": "$",
                "ResultPath": "$.Payload"
              },
              "Wait State": {
                "Type": "Wait",
                "Seconds": 3,
                "Next": "Lambda Square State"
              },
              "Lambda Square State": {
                "Type": "Task",
                "Resource": "${SquareLambdaArn}",
                "InputPath": "$.Payload",
                "ResultPath": "$.Payload",
                "End": true
              }
            }
          }
        - SumLambdaArn: !GetAtt StepFunctionExampleSumLambda.Arn
          SquareLambdaArn: !GetAtt StepFunctionExampleSquareLambda.Arn
