AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM Template for Lambda SAM local testing - Layers

Resources:
  # Lambda function with Layers
  LambdaLayersFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.lambda_handler
      CodeUri: lambda_layers_src/
      Runtime: python3.9
      Layers:
        - !Ref LambdaLayersLayer
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /path
            Method: get

  # Lambda layer for Lambda function
  LambdaLayersLayer:
    Type: AWS::Serverless::LayerVersion
    Properties:
      LayerName: CustomLambdaLayer1
      Description: Custom Lambda Layer for dependencies
      ContentUri: ./custom-lambda-layer/
      CompatibleRuntimes:
        - python3.9
    Metadata:
      BuildMethod: python3.9
