version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - cd ./java-appsync-sam
  build:
    commands:
      - echo Build started on `date`
      - mvn package 
  post_build:
    commands:
      - echo Build completed on `date`
      - sam package --template template.yaml --s3-bucket $BUILD_OUTPUT_BUCKET --output-template-file application.yaml
artifacts:
  files:
    - ./java-appsync-sam/target/java-appsync-sam-1.0-SNAPSHOT.jar
    - ./java-appsync-sam/appspec.yml
    - ./java-appsync-sam/application.yaml
    - ./java-appsync-sam/cognito.yaml
  discard-paths: yes